# Generated by Django 3.2 on 2022-02-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_entrega',
            new_name='Avaliacao',
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelTable(
            name='avaliacao',
            table='avaliacao',
        ),
    ]
